baseURL = "http://tickle.dev/"
languageCode = "en-us"
title = "Tickle.Dev"
theme = "sam"
description = "Embedded and real-time software development"
enableGitInfo = true
enableRobotsTXT = true
pygmentsUseClasses = true
pygmentsUseClassic = false
pygmentsCodefences = true

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[Author]
    name = "Steve Tickle"


[[params.mainMenu]]
    link = "/posts"
    text = "Articles"

[[params.mainMenu]]
    link = "/about"
    text = "Who am I?"


[params]
    footerText          = "[Tickle.Dev](http://Tickle.Dev), an embedded software consultancy"
    favicon             = "favicon.ico"

[params.assets]
customCSS = ["css/syntax.css"]


